import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Examen Final de DAW - Thomas Brandt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="col">
          <div className="row">
            <Link href="./question2">
              <a>Question 2</a>
            </Link>
          </div>
          <div className="row">
            <Link href="./question4">
              <a>Question 4</a>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
