import Head from "next/head";

import styles from "../styles/Question2.module.css";

import { useState } from "react";

const question2 = () => {
  const [value, setValue] = useState(0);

  return (
    <>
      <Head>
        <title>Question 4 -Examen Final de DAW - Thomas Brandt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mt-5">
          <div className="row justify-content-center">
            <div className="col-8">
              <div className="media">
                <img
                  src="images/barre-olympique.png"
                  className={`mr-3 ${styles.image_60}`}
                  alt="Barre olympique"
                />
                <div className="media-body">
                  <h5 className="mt-0">
                    BARRE OLYMPIQUE ROGUE 25MM IWF - CERAKOTE
                  </h5>
                  <h5 className="mt-0">CA$789.00</h5>
                  <hr />
                  <div className={`${styles.selecteur_quantite}`}>
                    <button
                      id="bouton-moins"
                      type="button"
                      className="btn btn-light bouton-quantite"
                      onClick={() => {
                        value - 1 >= 0 ? setValue(value - 1) : null;
                      }}
                    >
                      -
                    </button>
                    <span className={`form-control ${styles.champ_quantite}`}>
                      {value}
                    </span>
                    <button
                      id="bouton-plus"
                      type="button"
                      className="btn btn-light bouton-quantite"
                      onClick={() => setValue(value + 1)}
                    >
                      +
                    </button>
                  </div>
                  <button
                    id="bouton-ajout-panier"
                    type="button"
                    className={`btn btn-primary btn-block ${
                      value <= 0 && "disabled"
                    }`}
                    onClick={() =>
                      value > 0 && console.log(`la valeur est de ${value}`)
                    }
                  >
                    Ajouter au panier
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default question2;
